maxActionDistance: 16.0
maxRapeDistance: 5.0
maxDaysWithoutInteraction: 14
warningDaysWithoutInteraction: 13
sneakKissCooldownSeconds: 5

police:
  group: "police"

topMarriages:
  header: "<gold><bold>Топ браков</bold></gold>"
  footer: "<gray>Новые браки попадают сюда автоматически.</gray>"
