name: BloodRP
version: '1.0-SNAPSHOT'
main: boo.bloodstone.bloodsex.BloodRP
api-version: '1.21.11'
folia-supported: true

permissions:
  bloodrp.sex:
    description: Generic Permission for all commands
    default: op
  bloodrp.rape:
    description: Permission for direct actions without accept
    default: op
  bloodrp.rape.immune:
    description: Players with this permission cannot be raped
    default: false

depend: [CommonBloodLib, GSit, BetterModel]
